/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaisSlugRouteImport } from './routes/pais.$slug'
import { Route as BrincadeirasGameIdRouteImport } from './routes/brincadeiras.$gameId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaisSlugRoute = PaisSlugRouteImport.update({
  id: '/pais/$slug',
  path: '/pais/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrincadeirasGameIdRoute = BrincadeirasGameIdRouteImport.update({
  id: '/brincadeiras/$gameId',
  path: '/brincadeiras/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/brincadeiras/$gameId': typeof BrincadeirasGameIdRoute
  '/pais/$slug': typeof PaisSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/brincadeiras/$gameId': typeof BrincadeirasGameIdRoute
  '/pais/$slug': typeof PaisSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/brincadeiras/$gameId': typeof BrincadeirasGameIdRoute
  '/pais/$slug': typeof PaisSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lobby' | '/login' | '/brincadeiras/$gameId' | '/pais/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lobby' | '/login' | '/brincadeiras/$gameId' | '/pais/$slug'
  id:
    | '__root__'
    | '/'
    | '/lobby'
    | '/login'
    | '/brincadeiras/$gameId'
    | '/pais/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LobbyRoute: typeof LobbyRoute
  LoginRoute: typeof LoginRoute
  BrincadeirasGameIdRoute: typeof BrincadeirasGameIdRoute
  PaisSlugRoute: typeof PaisSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pais/$slug': {
      id: '/pais/$slug'
      path: '/pais/$slug'
      fullPath: '/pais/$slug'
      preLoaderRoute: typeof PaisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brincadeiras/$gameId': {
      id: '/brincadeiras/$gameId'
      path: '/brincadeiras/$gameId'
      fullPath: '/brincadeiras/$gameId'
      preLoaderRoute: typeof BrincadeirasGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LobbyRoute: LobbyRoute,
  LoginRoute: LoginRoute,
  BrincadeirasGameIdRoute: BrincadeirasGameIdRoute,
  PaisSlugRoute: PaisSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
